from textwrap import dedent

question_bank = {
    'AIDS': {
        'name': 'Artificial Intelligence & Data Science',
        'timer': 600,
        'level': 'Hard',
        'subjects': [
            ('aids-ml', 'Machine Learning', '🤖', [
                ('Which algorithm is an example of supervised learning?', ['K-Means', 'Decision Trees', 'Apriori', 'DBSCAN'], 1),
                ('What is the primary goal of regression models?', ['Classify labels', 'Predict continuous values', 'Cluster similar records', 'Reduce dimensionality'], 1),
                ('Which metric best describes model generalization on new data?', ['Training accuracy', 'Validation accuracy', 'Loss on training data', 'Number of features'], 1),
                ('What technique helps prevent overfitting?', ['Removing validation data', 'Using regularization', 'Increasing model depth indefinitely', 'Ignoring feature scaling'], 1),
                ('Which method combines several base learners?', ['PCA', 'Bootstrap', 'Ensemble learning', 'Feature selection'], 2),
                ('What is a common loss function for classification?', ['Mean squared error', 'Mean absolute error', 'Cross entropy', 'Euclidean distance'], 2),
                ('Which algorithm is instance-based?', ['Linear regression', 'KNN', 'Logistic regression', 'Naive Bayes'], 1),
                ('Batch gradient descent updates parameters using?', ['Entire dataset', 'A single sample', 'Only validation set', 'Only test set'], 0),
                ('What is the purpose of feature scaling?', ['Increase model complexity', 'Normalize numeric ranges', 'Create new features', 'Remove categorical values'], 1),
                ('Which problem type uses a regression model?', ['Predicting stock prices', 'Classifying emails', 'Clustering customers', 'Finding association rules'], 0),
            ]),
            ('aids-dl', 'Deep Learning', '🧠', [
                ('Which architecture is widely used for image classification?', ['RNN', 'CNN', 'SVM', 'KNN'], 1),
                ('What does ReLU stand for in neural networks?', ['Rectified Linear Unit', 'Random Linear Update', 'Recursive Learning Unit', 'Recurrent Linear Unit'], 0),
                ('Which problem does backpropagation solve?', ['Feature selection', 'Weight optimization', 'Data normalization', 'Clustering'], 1),
                ('Which layer type is commonly used in CNNs?', ['Dense layer', 'Convolutional layer', 'Softmax layer', 'Decision tree'], 1),
                ('Which network type handles sequential text data?', ['MLP', 'RNN', 'KNN', 'PCA'], 1),
                ('What is dropout used for?', ['Data preprocessing', 'Preventing overfitting', 'Improving label quality', 'Faster inference'], 1),
                ('What is a decoder in encoder-decoder models?', ['Feature scaler', 'A layer sequence that generates output', 'A loss function', 'A dataset split'], 1),
                ('Which activation is used for binary classification output?', ['Softmax', 'ReLU', 'Sigmoid', 'Tanh'], 2),
                ('What is transfer learning?', ['Converting text to speech', 'Using a pre-trained model', 'Scaling features', 'Hyperparameter tuning'], 1),
                ('Which library is commonly used for deep learning in Python?', ['React', 'Pandas', 'PyTorch', 'Flask'], 2),
            ]),
            ('aids-ds', 'Data Science', '📊', [
                ('What is data wrangling?', ['Collecting user feedback', 'Cleaning and preparing data', 'Training a model', 'Computing accuracy'], 1),
                ('Which step comes after data exploration?', ['Model deployment', 'Feature engineering', 'Final grading', 'Project management'], 1),
                ('Which visualization is best for comparing categories?', ['Line chart', 'Histogram', 'Bar chart', 'Scatter plot'], 2),
                ('What does ETL mean?', ['Extract, Transform, Load', 'Estimate, Test, Learn', 'Evaluate, Train, Label', 'Encode, Transfer, Loop'], 0),
                ('Which type of data analysis summarizes past behavior?', ['Predictive', 'Prescriptive', 'Descriptive', 'Diagnostic'], 2),
                ('What is a common tool for data analysis in Python?', ['TensorFlow', 'NumPy', 'Express', 'Docker'], 1),
                ('Which correlation value indicates a strong positive relationship?', ['-0.9', '0.0', '0.4', '0.8'], 3),
                ('What is the purpose of a pivot table?', ['Database indexing', 'Summarizing and aggregating data', 'Image processing', 'System deployment'], 1),
                ('Which data type is categorical?', ['Age', 'Salary', 'Product type', 'Test score'], 2),
                ('What is the first step in a data science workflow?', ['Model training', 'Data collection', 'Hyperparameter tuning', 'Report generation'], 1),
            ]),
            ('aids-python', 'Python Programming', '🐍', [
                ('Which keyword defines a function in Python?', ['func', 'def', 'function', 'lambda'], 1),
                ('What is the output of len([1, 2, 3])?', ['2', '3', '4', 'Error'], 1),
                ('Which data structure is ordered and mutable?', ['Tuple', 'List', 'Set', 'Dictionary'], 1),
                ('What does PEP8 focus on?', ['Package management', 'Coding style guidelines', 'Database connection', 'Deployment'], 1),
                ('Which method adds an item to a list?', ['append()', 'add()', 'push()', 'insert()'], 0),
                ('How do you start a for loop over a range?', ['for i from 0', 'for i in range(5)', 'foreach i in range(5)', 'loop i in range(5)'], 1),
                ('Which statement handles exceptions?', ['try/except', 'if/else', 'switch/case', 'when/then'], 0),
                ('What is a Python generator?', ['A type of list', 'A lazy iterator', 'A database', 'A compiled file'], 1),
                ('Which symbol begins a comment?', ['//', '#', '/*', '<!--'], 1),
                ('How do you import a module?', ['#import math', 'import math', 'require("math")', 'include math'], 1),
            ]),
            ('aids-ai', 'Artificial Intelligence', '🧠', [
                ('Which field focuses on agents that perceive and act?', ['Cybersecurity', 'Artificial Intelligence', 'Structural Engineering', 'Database Management'], 1),
                ('What is the Turing Test used to evaluate?', ['Robot speed', 'Machine intelligence', 'Data quality', 'Network throughput'], 1),
                ('Which agent type uses rules to make decisions?', ['Neural agent', 'Rule-based system', 'Genetic algorithm', 'Clustering agent'], 1),
                ('Which search strategy explores breadth first?', ['Breadth-first search', 'Depth-first search', 'Greedy search', 'A* search'], 0),
                ('What is knowledge representation?', ['Storing training data', 'Encoding information for reasoning', 'Scaling features', 'Deploying models'], 1),
                ('What is an expert system?', ['A database', 'A rule-based AI program', 'A visualization tool', 'A compiler'], 1),
                ('Which task does AI scheduling solve?', ['Summing numbers', 'Resource allocation', 'Writing text', 'Rendering graphics'], 1),
                ('What is a heuristic?', ['Exact solution', 'Approximate rule of thumb', 'Data distribution', 'Programming language'], 1),
                ('What does NLP stand for?', ['Natural Language Processing', 'Neural Learning Program', 'Network Layer Protocol', 'Nonlinear Prediction'], 0),
                ('Which is an example of symbolic AI?', ['Decision trees', 'Linear regression', 'Logic programming', 'Neural networks'], 2),
            ]),
            ('aids-nlp', 'NLP', '🗣️', [
                ('What is tokenization in NLP?', ['Splitting text into units', 'Training a model', 'Evaluating accuracy', 'Cleaning data'], 0),
                ('Which technique converts words to vectors?', ['One-hot encoding', 'Embedding', 'Both', 'Neither'], 2),
                ('What is stopword removal?', ['Deleting ignored words', 'Normalizing numbers', 'Stemming verbs', 'Training language models'], 0),
                ('Which model is used for language translation?', ['GAN', 'Seq2Seq', 'SVM', 'KNN'], 1),
                ('What does POS tagging assign?', ['Part of speech labels', 'Probability scores', 'Sentence length', 'Topic names'], 0),
                ('Which library is common for NLP in Python?', ['BeautifulSoup', 'NLTK', 'Pandas', 'Flask'], 1),
                ('What is sentiment analysis?', ['Detecting emotions in text', 'Analyzing images', 'Clustering users', 'Encrypting data'], 0),
                ('What is named entity recognition?', ['Identifying people, places, or organizations', 'Sorting datasets', 'Measuring similarity', 'Optimizing code'], 0),
                ('Which model uses attention for sequence tasks?', ['Random Forest', 'Transformers', 'KNN', 'Naive Bayes'], 1),
                ('Which step normalizes word forms?', ['Lemmatization', 'Classification', 'Clustering', 'Regression'], 0),
            ]),
            ('aids-cv', 'Computer Vision', '🖼️', [
                ('Which task identifies objects in images?', ['Classification', 'Detection', 'Regression', 'Clustering'], 1),
                ('What does CNN stand for?', ['Convolutional Neural Network', 'Central Network Node', 'Computer Numeric Control', 'Cascaded Neural Node'], 0),
                ('What is image segmentation?', ['Separating foreground and background', 'Compressing images', 'Filtering noise', 'Translating text'], 0),
                ('Which filter detects edges?', ['Gaussian', 'Sobel', 'Linear', 'KNN'], 1),
                ('What does RGB represent?', ['Red Green Blue', 'Random Gradient Boost', 'Recursive Graph Builder', 'Real Gaussian Blur'], 0),
                ('Which technique reduces image size?', ['Normalization', 'Downsampling', 'Upsampling', 'Tokenization'], 1),
                ('What is optical flow used for?', ['Image classification', 'Motion tracking', 'Text parsing', 'Speech recognition'], 1),
                ('Which method helps with low-light images?', ['Data augmentation', 'Histogram equalization', 'Overfitting', 'Normalization'], 1),
                ('What is feature extraction?', ['Creating new images', 'Identifying important patterns', 'Encrypting pixels', 'Sorting labels'], 1),
                ('Which model is used for style transfer?', ['ResNet', 'U-Net', 'GAN', 'SVM'], 2),
            ]),
            ('aids-statistics', 'Statistics', '📈', [
                ('What does mean measure?', ['Center of data', 'Spread of data', 'Shape of distribution', 'Correlation'], 0),
                ('Which value is a measure of spread?', ['Mean', 'Median', 'Standard deviation', 'Mode'], 2),
                ('What is a p-value?', ['Probability of observing data under null hypothesis', 'Sample size', 'Model accuracy', 'Learning rate'], 0),
                ('Which distribution is symmetric?', ['Normal distribution', 'Exponential distribution', 'Poisson distribution', 'Chi-square distribution'], 0),
                ('What is a null hypothesis?', ['A hypothesis of no effect', 'A preferred outcome', 'A type of model', 'A feature selection method'], 0),
                ('Which measure indicates skewness?', ['Mean', 'Kurtosis', 'Skew coefficient', 'Standard error'], 2),
                ('What does covariance show?', ['Relationship between two variables', 'Average value', 'Model complexity', 'Probability mass'], 0),
                ('What is a confidence interval?', ['Range of estimates around a statistic', 'Another name for standard deviation', 'A type of test', 'An optimization metric'], 0),
                ('Which test compares means of two groups?', ['ANOVA', 't-test', 'Chi-square', 'Regression'], 1),
                ('Which sampling method is random?', ['Stratified', 'Convenience', 'Simple random', 'Judgmental'], 2),
            ]),
        ],
    },
    'IT': {
        'name': 'Information Technology',
        'timer': 560,
        'level': 'Medium',
        'subjects': [
            ('it-networking', 'Networking', '🌐', [
                ('Which layer of the OSI model is responsible for routing?', ['Physical', 'Network', 'Data Link', 'Application'], 1),
                ('What does TCP guarantee?', ['Fast delivery', 'Connectionless service', 'Reliable delivery', 'Broadcast transmission'], 2),
                ('Which address uniquely identifies a device on a network?', ['MAC address', 'IP address', 'Port number', 'Subnet mask'], 0),
                ('What protocol is used to resolve IP addresses?', ['HTTP', 'DNS', 'ARP', 'SMTP'], 2),
                ('Which topology connects each node to a central hub?', ['Bus', 'Ring', 'Star', 'Mesh'], 2),
                ('What is a VLAN used for?', ['Virtual network isolation', 'File storage', 'Power distribution', 'Database indexing'], 0),
                ('Which port is default for HTTPS?', ['80', '21', '443', '25'], 2),
                ('What is bandwidth?', ['Amount of data transferred over time', 'Number of connected devices', 'Signal strength', 'Packet size'], 0),
                ('Which protocol is used for email retrieval?', ['POP3', 'FTP', 'SNMP', 'SSH'], 0),
                ('What does NAT do?', ['Encrypts traffic', 'Translates private to public IPs', 'Allocates bandwidth', 'Monitors network health'], 1),
            ]),
            ('it-cloud', 'Cloud Computing', '☁️', [
                ('Which service model provides applications over the internet?', ['IaaS', 'PaaS', 'SaaS', 'DaaS'], 2),
                ('What is scalability in cloud computing?', ['Reducing users', 'Adjusting resources to demand', 'Increasing latency', 'Encrypting data'], 1),
                ('Which cloud type is owned by a third party?', ['Private cloud', 'Public cloud', 'On-premise', 'Hybrid cloud'], 1),
                ('What is an example of IaaS?', ['Virtual machines', 'Managed database service', 'Web browser', 'Email client'], 0),
                ('What does elasticity allow?', ['Fixed resources', 'Automatic scaling', 'Manual backup', 'Data encryption'], 1),
                ('Which tool manages infrastructure as code?', ['Terraform', 'Photoshop', 'Excel', 'Notepad'], 0),
                ('What is a cloud region?', ['Data center location', 'Security protocol', 'Storage format', 'Programming language'], 0),
                ('Which benefit is associated with cloud adoption?', ['Higher hardware costs', 'Greater flexibility', 'Reduced network speed', 'Manual provisioning'], 1),
                ('What does multi-tenancy mean?', ['Multiple protocols', 'Multiple users share the same infrastructure', 'Multiple networks', 'Multiple databases'], 1),
                ('Which term refers to pay-as-you-go computing?', ['Reserved instance', 'Subscription', 'On-demand', 'License'], 2),
            ]),
            ('it-database', 'Database Management', '🗄️', [
                ('Which query retrieves data from a table?', ['INSERT', 'UPDATE', 'DELETE', 'SELECT'], 3),
                ('What is normalization used for?', ['Improving query speed', 'Reducing data redundancy', 'Encrypting records', 'Visualizing data'], 1),
                ('What does ACID stand for?', ['Atomicity, Consistency, Isolation, Durability', 'Availability, Consistency, Integrity, Durability', 'Authentication, Control, Integrity, Distribution', 'Access, Control, Isolation, Distribution'], 0),
                ('Which key uniquely identifies each row?', ['Foreign key', 'Primary key', 'Composite key', 'Candidate key'], 1),
                ('What is a join used for?', ['Compressing tables', 'Combining rows from multiple tables', 'Deleting duplicates', 'Normalizing data'], 1),
                ('Which DBMS model organizes data in tables?', ['Relational', 'NoSQL', 'Graph', 'Document'], 0),
                ('What is a transaction?', ['Formula calculation', 'Unit of work that is atomic', 'Backup file', 'Data index'], 1),
                ('Which statement adds a new row?', ['UPDATE', 'INSERT', 'SELECT', 'CREATE'], 1),
                ('What is denormalization?', ['Splitting tables', 'Combining tables for performance', 'Encrypting data', 'Backing up databases'], 1),
                ('Which SQL clause filters rows?', ['GROUP BY', 'ORDER BY', 'WHERE', 'HAVING'], 2),
            ]),
            ('it-cybersecurity', 'Cyber Security', '🔒', [
                ('What is phishing?', ['Network scanning', 'Fake emails that steal information', 'Data encryption', 'Firewall blocking'], 1),
                ('Which technique helps secure web traffic?', ['HTTP', 'FTP', 'SSL/TLS', 'SMTP'], 2),
                ('What is a strong password property?', ['Short length', 'Common words', 'Complex combination', 'Simple sequence'], 2),
                ('Which authentication factor uses biometrics?', ['Something you know', 'Something you have', 'Something you are', 'Something you do'], 2),
                ('What does MFA mean?', ['Multiple file access', 'Multi-factor authentication', 'Machine failure analysis', 'Modular function algorithm'], 1),
                ('Which tool detects intrusions on a network?', ['IDS', 'CPU', 'DNS', 'FTP'], 0),
                ('What is encryption used for?', ['Data compression', 'Data visualization', 'Data protection', 'Data backup'], 2),
                ('Which attack intercepts communication between parties?', ['SQL injection', 'Man-in-the-middle', 'Brute force', 'Spoofing'], 1),
                ('Which protocol is secure for remote login?', ['Telnet', 'HTTP', 'SSH', 'SMTP'], 2),
                ('What is a firewall?', ['Network security barrier', 'Database storage', 'Programming language', 'Design pattern'], 0),
            ]),
            ('it-web', 'Web Technologies', '🕸️', [
                ('Which language is used for page structure?', ['CSS', 'JavaScript', 'HTML', 'SQL'], 2),
                ('What does CSS control?', ['Behavior', 'Structure', 'Style', 'Security'], 2),
                ('Which framework is used for React apps?', ['Laravel', 'Angular', 'Next.js', 'TensorFlow'], 2),
                ('What is REST?', ['A database model', 'A web service architecture style', 'A security protocol', 'A programming language'], 1),
                ('Which language is executed in the browser?', ['Python', 'C++', 'JavaScript', 'Java'], 2),
                ('What does DOM stand for?', ['Document Object Model', 'Data Order Management', 'Digital Object Method', 'Domain Object Model'], 0),
                ('Which tag links CSS to HTML?', ['<script>', '<link>', '<style>', '<meta>'], 1),
                ('What is responsive design?', ['Static layouts only', 'Design that adapts to screen size', 'Server-side rendering', 'Database structure'], 1),
                ('Which HTTP method retrieves data?', ['POST', 'GET', 'DELETE', 'PUT'], 1),
                ('What is a single-page application?', ['A website with one HTML file that dynamically updates', 'A mobile app', 'A desktop program', 'A database schema'], 0),
            ]),
            ('it-software', 'Software Engineering', '🧩', [
                ('What does SDLC stand for?', ['Software Development Life Cycle', 'System Design Lifecycle', 'Secure Data Life Code', 'Software Deployment Life Cycle'], 0),
                ('Which model is iterative and adaptive?', ['Waterfall', 'Agile', 'V-model', 'Spiral'], 1),
                ('What is unit testing?', ['Testing individual components', 'Testing whole system', 'Deploying software', 'Writing code documentation'], 0),
                ('What is refactoring?', ['Changing functionality', 'Improving code structure without changing behavior', 'Deleting code', 'Designing user interfaces'], 1),
                ('Which activity gathers user requirements?', ['Validation', 'Verification', 'Requirement analysis', 'Maintenance'], 2),
                ('What is a use case?', ['A hardware component', 'A software testing tool', 'A description of system interactions', 'A programming language'], 2),
                ('Which metric measures code readability?', ['Cyclomatic complexity', 'LOC', 'Page ranking', 'Cluster density'], 1),
                ('What is version control used for?', ['Deploying software', 'Managing code changes', 'Designing databases', 'Monitoring servers'], 1),
                ('Which document describes software behavior?', ['SRS', 'HTML', 'CSS', 'SQL'], 0),
                ('What is a design pattern?', ['A repeating design element', 'A reusable solution to common problems', 'A test case', 'A user interface layout'], 1),
            ]),
            ('it-os', 'Operating Systems', '⚙️', [
                ('Which component manages hardware resources?', ['Compiler', 'Operating system', 'Database', 'Interpreter'], 1),
                ('What is virtual memory?', ['Physical RAM only', 'A disk-backed extension of RAM', 'GPU memory', 'Cache memory'], 1),
                ('Which scheduling algorithm is preemptive?', ['FCFS', 'Round Robin', 'SPN', 'None'], 1),
                ('What does multitasking allow?', ['Compressing files', 'Running multiple processes concurrently', 'Encrypting data', 'Improving battery life'], 1),
                ('What is a process?', ['A program in execution', 'A data file', 'A user account', 'A hardware device'], 0),
                ('Which structure stores activated processes?', ['File table', 'Process control block', 'Cache', 'Buffer'], 1),
                ('What is deadlock?', ['A locked file', 'Mutual waiting among processes', 'A processor fault', 'A memory leak'], 1),
                ('Which memory allocation is dynamic?', ['Static allocation', 'Heap allocation', 'ROM allocation', 'Cache allocation'], 1),
                ('Which OS service handles I/O devices?', ['Scheduler', 'Memory manager', 'Device manager', 'Loader'], 2),
                ('What does kernel mode allow?', ['User applications only', 'Direct hardware access', 'Remote login only', 'Graphics rendering only'], 1),
            ]),
            ('it-infrastructure', 'IT Infrastructure', '🖧', [
                ('What does data center infrastructure include?', ['Only servers', 'Servers, storage, network, and cooling', 'Mobile apps', 'Programming languages'], 1),
                ('Which component provides power redundancy?', ['Firewall', 'UPS', 'Router', 'Switch'], 1),
                ('What is virtualization?', ['Creating virtual machines on physical hardware', 'Data encryption', 'Network routing', 'Database replication'], 0),
                ('Which device connects multiple networks?', ['Switch', 'Load balancer', 'Router', 'Hub'], 2),
                ('What is SLA in IT services?', ['Service Level Agreement', 'System Load Average', 'Secure Login Authorization', 'Server Link Access'], 0),
                ('Which technology offers remote access to servers?', ['SSH', 'HTML', 'CSS', 'SSL'], 0),
                ('What is RAID used for?', ['Authentication', 'Fault-tolerant storage', 'Network routing', 'User management'], 1),
                ('Which term refers to infrastructure components managed remotely?', ['On-premise', 'Cloud', 'Hosted', 'Embedded'], 1),
                ('What does DNS resolve?', ['Domain names to IP addresses', 'Passwords', 'Email', 'Files'], 0),
                ('Which system monitors infrastructure health?', ['CMS', 'SMS', 'NMS', 'IDS'], 2),
            ]),
        ],
    },
    'CSE': {
        'name': 'Computer Science & Engineering',
        'timer': 620,
        'level': 'Hard',
        'subjects': [
            ('cse-programming', 'Programming', '💻', [
                ('What is the output of 2 + 3 * 4 in most languages?', ['20', '14', '18', '12'], 1),
                ('Which keyword declares a constant in modern JavaScript?', ['var', 'let', 'const', 'function'], 2),
                ('What is recursion?', ['Looping through data', 'Function calling itself', 'Sorting an array', 'Compiling code'], 1),
                ('Which construct is used for conditional execution?', ['for', 'while', 'if', 'switch'], 2),
                ('What is a data type for true/false values?', ['int', 'string', 'boolean', 'float'], 2),
                ('Which error occurs when a variable is undefined?', ['Syntax error', 'Runtime error', 'Type error', 'Logical error'], 1),
                ('What does API stand for?', ['Application Programming Interface', 'Advanced Process Input', 'Automatic Program Installer', 'Analytics Processing Interface'], 0),
                ('What is a loop that never ends called?', ['Conditional loop', 'Infinite loop', 'Recursive loop', 'For loop'], 1),
                ('Which operator tests equality without type conversion in JavaScript?', ['==', '!=', '===', '=>'], 2),
                ('What is object-oriented programming?', ['Procedural style', 'Using objects and classes', 'Writing scripts only', 'Querying databases'], 1),
            ]),
            ('cse-data-structures', 'Data Structures', '🧱', [
                ('Which structure uses LIFO?', ['Queue', 'Stack', 'Tree', 'Graph'], 1),
                ('Which operation inserts at the end of a list?', ['Push', 'Pop', 'Dequeue', 'Peek'], 0),
                ('What is a balanced tree?', ['All leaves at same depth', 'Height difference <=1', 'Only left children', 'One node only'], 1),
                ('Which structure stores key-value pairs?', ['Array', 'Queue', 'Hash table', 'Stack'], 2),
                ('What is the worst-case time for searching an unsorted array?', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 2),
                ('What is a priority queue?', ['Queue sorted by priority', 'Normal FIFO queue', 'Circular queue', 'Stack'], 0),
                ('Which traversal visits root after children?', ['Inorder', 'Preorder', 'Postorder', 'Level order'], 2),
                ('Which structure is suitable for BFS?', ['Stack', 'Queue', 'Heap', 'Tree'], 1),
                ('What is a heap?', ['Unsorted list', 'Complete binary tree', 'Graph type', 'Hash table'], 1),
                ('Which structure uses nodes and edges?', ['Array', 'Graph', 'Stack', 'Queue'], 1),
            ]),
            ('cse-algorithms', 'Algorithms', '🧠', [
                ('Which algorithm is divide-and-conquer?', ['Linear search', 'Quick sort', 'Bubble sort', 'Selection sort'], 1),
                ('What is the average time complexity of merge sort?', ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'], 1),
                ('Which algorithm finds shortest paths from one source?', ['Prim', 'Kruskal', 'Dijkstra', 'Floyd-Warshall'], 2),
                ('What is greedy algorithm strategy?', ['Try all solutions', 'Make locally optimal choices', 'Use recursion only', 'Optimize memory usage'], 1),
                ('Which algorithm uses dynamic programming?', ['Binary search', 'Fibonacci with memoization', 'Insertion sort', 'DFS'], 1),
                ('What is complexity of binary search?', ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], 1),
                ('Which problem is NP-hard?', ['Sorting', 'Graph traversal', 'Traveling salesman', 'Linear search'], 2),
                ('What is a heuristic?', ['Exact solution', 'Approximate strategy', 'Data structure', 'Programming language'], 1),
                ('Which algorithm sorts in place?', ['Merge sort', 'Quick sort', 'Radix sort', 'Counting sort'], 1),
                ('What does Big O describe?', ['Memory usage', 'Algorithm growth rate', 'CPU temperature', 'Network latency'], 1),
            ]),
            ('cse-os', 'Operating Systems', '🖥️', [
                ('Which scheduler selects processes for execution?', ['CPU scheduler', 'Memory manager', 'File system', 'Device driver'], 0),
                ('What is a page fault?', ['Missing disk sector', 'Requested page not in memory', 'Broken application', 'IO failure'], 1),
                ('Which memory is fastest?', ['Cache', 'RAM', 'Hard disk', 'Registers'], 3),
                ('What does context switch involve?', ['Changing running process state', 'Loading a file', 'Encrypting data', 'Compiling code'], 0),
                ('Which resource is managed by the OS?', ['User passwords', 'Hardware devices', 'Web pages', 'Database records'], 1),
                ('What is a kernel?', ['User interface', 'Core OS component', 'Application program', 'Database engine'], 1),
                ('What is deadlock avoidance?', ['Ignoring deadlocks', 'Preventing unsafe resource allocation', 'Scheduling processes randomly', 'Removing CPUs'], 1),
                ('Which state means process ready but not running?', ['Running', 'Waiting', 'Ready', 'Terminated'], 2),
                ('What is virtual memory?', ['RAM only', 'Disk-backed RAM extension', 'CPU cache', 'GPU memory'], 1),
                ('Which system call loads a program?', ['open', 'exec', 'write', 'read'], 1),
            ]),
            ('cse-dbms', 'DBMS', '📦', [
                ('Which model organizes data as relations?', ['Hierarchical', 'Network', 'Relational', 'Document'], 2),
                ('What is a foreign key?', ['Unique identifier', 'Attribute that references another table', 'Index type', 'Query command'], 1),
                ('What is SQL used for?', ['Styling sheets', 'Data manipulation and queries', 'Image processing', 'Network routing'], 1),
                ('Which normal form removes partial dependency?', ['1NF', '2NF', '3NF', 'BCNF'], 1),
                ('What is a view?', ['Physical table', 'Virtual table', 'Backup file', 'Index'], 1),
                ('Which storage engine is used by MySQL?', ['InnoDB', 'MongoDB', 'Redis', 'PostgreSQL'], 0),
                ('What is a transaction?', ['Single SQL statement', 'Atomic sequence of DB operations', 'Backup routine', 'Security policy'], 1),
                ('What does JOIN combine?', ['Rows from two tables', 'Columns from same table', 'Databases', 'Files'], 0),
                ('Which command removes a table?', ['DROP', 'DELETE', 'REMOVE', 'TRUNCATE'], 0),
                ('Which operation retrieves rows?', ['INSERT', 'SELECT', 'UPDATE', 'ALTER'], 1),
            ]),
            ('cse-networks', 'Computer Networks', '🌩️', [
                ('Which protocol is used for web traffic?', ['SMTP', 'FTP', 'HTTP', 'SSH'], 2),
                ('What is a subnet mask?', ['Network address', 'Rule for routing', 'Pattern that separates network and host bits', 'Security protocol'], 2),
                ('Which device forwards packets between networks?', ['Switch', 'Hub', 'Router', 'Access point'], 2),
                ('Which layer is responsible for end-to-end delivery?', ['Transport', 'Network', 'Data Link', 'Physical'], 0),
                ('What does DNS translate?', ['Hostnames to IPs', 'Emails to addresses', 'Files to folders', 'MACs to IPs'], 0),
                ('Which address is assigned to a network interface?', ['IP address', 'MAC address', 'Port number', 'Subnet mask'], 1),
                ('What does DHCP provide?', ['Static IPs', 'Dynamic IP addresses', 'Encryption keys', 'Firewall rules'], 1),
                ('Which topology connects nodes in a circle?', ['Star', 'Bus', 'Ring', 'Mesh'], 2),
                ('What is latency?', ['Delay in transmission', 'Packet size', 'Bandwidth', 'Signal strength'], 0),
                ('Which is a wireless protocol?', ['Ethernet', 'Bluetooth', 'Token ring', 'FDDI'], 1),
            ]),
            ('cse-software', 'Software Engineering', '📐', [
                ('Which model emphasizes customer collaboration?', ['Waterfall', 'V-model', 'Agile', 'Spiral'], 2),
                ('What is the main goal of requirements engineering?', ['Code generation', 'Understanding stakeholder needs', 'Deployment', 'Testing'], 1),
                ('What is a use case diagram used for?', ['Coding UI', 'Modeling system interactions', 'Database design', 'Network layout'], 1),
                ('What is code modularity?', ['Combining functions into one block', 'Dividing software into separate components', 'Writing comments', 'Compiling code'], 1),
                ('Which phase tests integration between modules?', ['Unit testing', 'Integration testing', 'Acceptance testing', 'Maintenance'], 1),
                ('What is version control?', ['Managing code changes over time', 'Controlling versions of documents', 'Testing software', 'Deploying servers'], 0),
                ('What is software maintenance?', ['Developing new features only', 'Updating and fixing existing software', 'Writing requirements', 'Installing OS'], 1),
                ('Which activity defines functional requirements?', ['Design', 'Testing', 'Requirement gathering', 'Deployment'], 2),
                ('What is a prototype?', ['Final product', 'Early working model', 'Database schema', 'Deployment script'], 1),
                ('What is risk management in SE?', ['Avoiding all problems', 'Identifying and mitigating project risks', 'Writing code faster', 'Ignoring bugs'], 1),
            ]),
            ('cse-compiler', 'Compiler Design', '🛠️', [
                ('What is lexical analysis?', ['Parsing source code into tokens', 'Generating machine code', 'Optimizing programs', 'Linking libraries'], 0),
                ('What is a token?', ['A hardware device', 'A program instruction', 'A lexical unit', 'A compiler error'], 2),
                ('Which phase builds the syntax tree?', ['Lexical analysis', 'Syntax analysis', 'Semantic analysis', 'Code generation'], 1),
                ('What is the purpose of optimization?', ['Make code unreadable', 'Improve performance', 'Increase file size', 'Translate to source code'], 1),
                ('Which grammar is used for parsing?', ['Regular grammar', 'Context-free grammar', 'Unrestricted grammar', 'No grammar'], 1),
                ('What does an interpreter do?', ['Transforms code to machine code and executes it directly', 'Compiles and stores binary only', 'Formats text', 'Runs queries'], 0),
                ('What is syntax error?', ['Logical mistake', 'Violation of grammar rules', 'Runtime failure', 'Incorrect output'], 1),
                ('What is code generation?', ['Creating tokens', 'Translating intermediate code into target code', 'Scanning input', 'Installing software'], 1),
                ('Which structure represents syntax?', ['Parse tree', 'Hash table', 'Queue', 'Stack'], 0),
                ('What is symbol table used for?', ['Storing lexical tokens', 'Keeping identifiers and types', 'Rendering graphics', 'Managing memory'], 1),
            ]),
        ],
    },
    'ECE': {
        'name': 'Electronics & Communication Engineering',
        'timer': 600,
        'level': 'Hard',
        'subjects': [
            ('ece-digital', 'Digital Electronics', '🔌', [
                ('Which logic gate outputs true only when both inputs are true?', ['OR', 'AND', 'NOT', 'XOR'], 1),
                ('What does flip-flop store?', ['A logic gate', 'A bit of memory', 'A transistor count', 'A resistor value'], 1),
                ('Which number system is binary?', ['Base 2', 'Base 8', 'Base 10', 'Base 16'], 0),
                ('What does a multiplexer do?', ['Selects one input to output', 'Adds two numbers', 'Stores data', 'Generates clock signals'], 0),
                ('Which circuit is combinational?', ['Latch', 'Adder', 'Flip-flop', 'Register'], 1),
                ('What is a decoder used for?', ['Combine signals', 'Translate coded input to outputs', 'Store data', 'Amplify signals'], 1),
                ('Which device converts binary to decimal?', ['Encoder', 'Decoder', 'Full adder', 'Multiplexer'], 1),
                ('What is propagation delay?', ['Time signal takes to traverse a circuit', 'Time to store data', 'Time for CPU to execute', 'Time to compile code'], 0),
                ('What is a Karnaugh map used for?', ['Timing analysis', 'Logic simplification', 'Power measurement', 'Signal filtering'], 1),
                ('Which logic family uses transistors and diodes?', ['CMOS', 'TTL', 'ECL', 'RTL'], 1),
            ]),
            ('ece-vlsi', 'VLSI Design', '🧩', [
                ('What does VLSI stand for?', ['Very Large Scale Integration', 'Variable Logic Signal Interface', 'Voltage Level Standard Input', 'Very Low Scale Implementation'], 0),
                ('Which device is primary in CMOS technology?', ['Resistor', 'Capacitor', 'MOSFET', 'Inductor'], 2),
                ('What is a standard cell library?', ['Collection of logic gates', 'Set of design rules', 'Database of IC layouts', 'Programming language library'], 0),
                ('What is stick diagram used for?', ['Layout planning', 'Simulation', 'Timing analysis', 'Power optimization'], 0),
                ('Which parameter affects propagation delay in VLSI?', ['Power supply only', 'Gate capacitance and resistance', 'Color of chip', 'Package size'], 1),
                ('What is floorplanning?', ['Placing blocks on chip', 'Writing software', 'Measuring voltage', 'Connecting wires'], 0),
                ('Which is a physical design step?', ['Logic synthesis', 'Placement and routing', 'Requirement gathering', 'Testing'], 1),
                ('What does fan-out mean?', ['Number of inputs a gate can drive', 'Number of outputs of a gate', 'Clock cycles per instruction', 'Power dissipation'], 0),
                ('Which fabrication process creates silicon patterns?', ['Photolithography', 'Etching', 'Doping', 'All of the above'], 3),
                ('What is chip yield?', ['Number of good chips produced', 'Number of transistors', 'Chip size', 'Clock speed'], 0),
            ]),
            ('ece-embedded', 'Embedded Systems', '🧠', [
                ('What is an embedded system?', ['Standalone PC', 'Computer built into another device', 'Cloud service', 'Database server'], 1),
                ('Which processor is common in embedded devices?', ['x86', 'ARM', 'PowerPC', 'MIPS'], 1),
                ('What is real-time operation?', ['Fast calculation', 'Guaranteed timing behavior', 'Batch processing', 'Offline analysis'], 1),
                ('Which interface is used for microcontroller programming?', ['UART', 'FTP', 'HTTP', 'SMTP'], 0),
                ('What is firmware?', ['User interface', 'Permanent software on hardware', 'Database record', 'Electrical circuit'], 1),
                ('Which bus connects peripherals in embedded systems?', ['I2C', 'SQL', 'CSS', 'HTML'], 0),
                ('What is polling?', ['Repeatedly checking device status', 'Interrupt handling', 'Memory allocation', 'Process scheduling'], 0),
                ('Which tool is used for debugging embedded software?', ['Oscilloscope', 'Compiler', 'Debugger', 'Router'], 2),
                ('What is a watchdog timer?', ['Performance monitor', 'Reset mechanism for failures', 'Temperature sensor', 'Power regulator'], 1),
                ('Which memory is non-volatile in embedded systems?', ['RAM', 'ROM', 'Cache', 'Register'], 1),
            ]),
            ('ece-signal', 'Signal Processing', '📡', [
                ('What is sampling?', ['Measuring signal amplitude at intervals', 'Filtering noise', 'Amplifying signal', 'Encoding data'], 0),
                ('Which transform converts signals to frequency domain?', ['Fourier transform', 'Laplace transform', 'Z-transform', 'Taylor series'], 0),
                ('What is a filter used for?', ['Increase noise', 'Modify signal spectrum', 'Store data', 'Schedule tasks'], 1),
                ('Which signal is analog?', ['Continuous signal', 'Discrete signal', 'Binary signal', 'Digital signal'], 0),
                ('What is aliasing?', ['Signal distortion due to undersampling', 'Perfect reconstruction', 'Amplification', 'Noise reduction'], 0),
                ('Which domain does FFT operate in?', ['Time', 'Frequency', 'Memory', 'Application'], 1),
                ('What is convolution?', ['Multiplying signals pointwise', 'Combining signals with integral operation', 'Encrypting data', 'Routing packets'], 1),
                ('Which component measures signal strength?', ['Transducer', 'Amplifier', 'Oscilloscope', 'Antenna'], 2),
                ('What is decimation?', ['Reducing sample rate', 'Increasing signal power', 'Filtering high frequencies', 'Converting analog to digital'], 0),
                ('What is signal-to-noise ratio?', ['Signal amplitude only', 'Noise amplitude only', 'Ratio of signal power to noise power', 'Transmission speed'], 2),
            ]),
            ('ece-analog', 'Analog Communication', '🎛️', [
                ('Which modulation varies amplitude?', ['AM', 'FM', 'PM', 'PWM'], 0),
                ('What is carrier frequency?', ['Frequency of original message', 'Frequency used to carry information', 'Sampling frequency', 'Bit rate'], 1),
                ('Which component converts analog signals to digital?', ['ADC', 'DAC', 'PLL', 'Mixer'], 0),
                ('What is a spectrum analyzer used for?', ['Measuring frequency components', 'Scaling signals', 'Coding data', 'Encrypting audio'], 0),
                ('Which noise type is thermal in origin?', ['Gaussian noise', 'Impulse noise', 'Quantization noise', 'Salt-and-pepper noise'], 0),
                ('What does SNR stand for?', ['Signal Normalization Ratio', 'Signal-to-Noise Ratio', 'System Network Rate', 'Serial Number Register'], 1),
                ('Which device combines signals of different frequencies?', ['Demodulator', 'Multiplexer', 'Mixer', 'Oscillator'], 2),
                ('What is AM radio an example of?', ['Digital communication', 'Analog communication', 'Optical communication', 'Packet switching'], 1),
                ('What is frequency modulation used for?', ['Vary amplitude', 'Vary frequency', 'Vary phase', 'Vary polarity'], 1),
                ('What does bandwidth measure?', ['Signal duration', 'Range of frequencies', 'Signal amplitude', 'Power consumption'], 1),
            ]),
            ('ece-micro', 'Microprocessors', '🧪', [
                ('What is the ALU used for?', ['Storing data', 'Arithmetic and logic operations', 'Power regulation', 'Signal transmission'], 1),
                ('Which bus carries data between CPU and memory?', ['Address bus', 'Control bus', 'Data bus', 'Power bus'], 2),
                ('What is an instruction set?', ['Collection of operations a CPU can execute', 'Set of memory addresses', 'Network protocol', 'Programming language'], 0),
                ('Which register holds the next instruction address?', ['ALU', 'Program counter', 'Stack pointer', 'Accumulator'], 1),
                ('What is pipelining in processors?', ['Executing multiple instructions overlapped in time', 'Storing data sequentially', 'Encrypting instructions', 'Cooling the CPU'], 0),
                ('Which memory is fastest and smallest?', ['RAM', 'Cache', 'ROM', 'Hard disk'], 1),
                ('What is an opcode?', ['A type of memory', 'Operation code for CPU instruction', 'Security key', 'Network packet'], 1),
                ('Which device interfaces with peripherals?', ['ALU', 'Control unit', 'I/O controller', 'Register'], 2),
                ('What does DMA do?', ['Direct memory access', 'Dynamic memory allocation', 'Distributed message architecture', 'Digital modulation analysis'], 0),
                ('Which processor architecture is RISC based?', ['x86', 'ARM', 'CISC', 'Itanium'], 1),
            ]),
            ('ece-control', 'Control Systems', '🎚️', [
                ('What is feedback in control systems?', ['Forward signal path', 'Using output to adjust input', 'Noise source', 'Power supply'], 1),
                ('Which system type has no steady-state error for a step input?', ['Type 0', 'Type 1', 'Type 2', 'Type 3'], 2),
                ('What is a transfer function?', ['Time domain response', 'Ratio of output to input in Laplace domain', 'Physical circuit layout', 'Sensor output'], 1),
                ('Which controller uses proportional, integral, and derivative actions?', ['PI controller', 'PD controller', 'PID controller', 'P controller'], 2),
                ('What does stability mean?', ['Output remains bounded for bounded input', 'Output always increases', 'System never responds', 'Control law changes'], 0),
                ('Which signal is used for correction in closed-loop?', ['Reference only', 'Error signal', 'Control signal', 'Disturbance'], 1),
                ('What is a root locus plot?', ['Frequency response chart', 'Plot showing closed-loop pole movement', 'Bode magnitude plot', 'Phase diagram'], 1),
                ('Which term describes system response speed?', ['Settling time', 'Bandwidth', 'Slew rate', 'All of the above'], 3),
                ('What is a plant in control?', ['Physical process being controlled', 'Control algorithm', 'Sensor', 'Actuator'], 0),
                ('Which device changes actuator input to system output?', ['Controller', 'Plant', 'Sensor', 'Disturbance'], 0),
            ]),
            ('ece-wireless', 'Wireless Communication', '📶', [
                ('Which band is used for Wi-Fi?', ['800 MHz', '2.4 GHz', '5 kHz', '60 GHz'], 1),
                ('What does LTE stand for?', ['Long Term Evolution', 'Low Throughput Ethernet', 'Lightwave Transmission Exchange', 'Local Transmission Endpoint'], 0),
                ('What is an antenna used for?', ['Generating power', 'Transmitting and receiving RF signals', 'Storing data', 'Encrypting traffic'], 1),
                ('Which modulation is used in digital wireless?', ['AM', 'FM', 'QAM', 'PCM'], 2),
                ('What is fading?', ['Signal loss due to path variations', 'Power increase', 'Latency reduction', 'Noise elimination'], 0),
                ('Which protocol is used in 5G?', ['LTE', 'WiMAX', 'NR', 'Bluetooth'], 2),
                ('What is a cell in mobile networks?', ['Geographic coverage area', 'Authentication token', 'Data packet', 'Control register'], 0),
                ('Which multiple access scheme uses different frequencies?', ['TDMA', 'FDMA', 'CDMA', 'SDMA'], 1),
                ('What is handover?', ['Switching between cell towers during movement', 'Encrypting voice calls', 'Compressing data', 'Generating control signals'], 0),
                ('Which layer handles physical transmission in wireless?', ['Network', 'Data Link', 'Physical', 'Application'], 2),
            ]),
        ],
    },
    'EEE': {
        'name': 'Electrical & Electronics Engineering',
        'timer': 580,
        'level': 'Medium',
        'subjects': [
            ('eee-power', 'Power Systems', '⚡', [
                ('What is a load flow study used for?', ['Determining voltage profile and power flows', 'Measuring efficiency', 'Designing transformers', 'Protecting lines'], 0),
                ('Which device steps up voltage for transmission?', ['Transformer', 'Generator', 'Circuit breaker', 'Relay'], 0),
                ('What is a bus in power systems?', ['Node where power is injected or drawn', 'Type of relay', 'Switchgear component', 'Transmission tower'], 0),
                ('Which system controls frequency and voltage?', ['Protection system', 'Control system', 'SCADA', 'Billing system'], 1),
                ('What does SCADA do?', ['Supervisory control and data acquisition', 'Simple circuit design', 'Signal conditioning', 'Storage control'], 0),
                ('Which fault increases current dramatically?', ['Open-circuit fault', 'Short-circuit fault', 'No-load fault', 'Line imbalance'], 1),
                ('What is synchronous generator used for?', ['Battery charging', 'AC power generation at constant speed', 'DC power generation', 'Signal processing'], 1),
                ('Which relay protects lines from faults?', ['Overcurrent relay', 'Temperature relay', 'Voltage regulator', 'Timer relay'], 0),
                ('What is power factor?', ['Ratio of real power to apparent power', 'Ratio of voltage to current', 'Energy efficiency', 'Frequency stability'], 0),
                ('Which network transmits high-voltage electricity?', ['Distribution network', 'Transmission network', 'Local area network', 'Wireless network'], 1),
            ]),
            ('eee-machines', 'Electrical Machines', '🏭', [
                ('What type of machine converts electrical to mechanical energy?', ['Generator', 'Motor', 'Transformer', 'Rectifier'], 1),
                ('Which machine has slip rings?', ['DC motor', 'Induction motor', 'Synchronous motor', 'Transformer'], 1),
                ('What is the purpose of an excitation system?', ['Cool the machine', 'Provide field current to rotor', 'Measure speed', 'Control voltage'], 1),
                ('Which machine has constant speed under load with synchronous speed?', ['DC motor', 'Induction motor', 'Synchronous motor', 'Stepper motor'], 2),
                ('What is a commutator used in?', ['Transformers', 'DC machines', 'Capacitors', 'Inductors'], 1),
                ('Which machine runs on single-phase supply?', ['Three-phase induction motor', 'Universal motor', 'Synchronous generator', 'Stepper motor'], 1),
                ('What does torque measure?', ['Voltage', 'Current', 'Rotational force', 'Power factor'], 2),
                ('Which motor is self-starting and widely used in fans?', ['Synchronous motor', 'Induction motor', 'DC motor', 'Stepper motor'], 1),
                ('What is no-load test used to find?', ['Efficiency', 'Copper loss', 'Core loss', 'Speed'], 2),
                ('Which machine is used in servo systems for precise control?', ['Induction motor', 'Stepper motor', 'Synchronous generator', 'Transformer'], 1),
            ]),
            ('eee-circuit', 'Circuit Theory', '🔋', [
                ('Ohm’s law relates voltage, current, and what?', ['Power', 'Resistance', 'Capacitance', 'Inductance'], 1),
                ('What is impedance?', ['Only resistance', 'Combined resistance and reactance', 'Only capacitance', 'Only inductance'], 1),
                ('What is a series circuit?', ['Components share the same current', 'Components share the same voltage', 'No current flow', 'Parallel connection'], 0),
                ('What is Kirchhoff’s current law?', ['Sum of currents at a node equals zero', 'Sum of voltages in a loop equals zero', 'Power is conserved', 'Impedance is constant'], 0),
                ('What does a capacitor store?', ['Charge', 'Magnetic field', 'Heat', 'Light'], 0),
                ('Which component opposes change in current?', ['Resistor', 'Capacitor', 'Inductor', 'Diode'], 2),
                ('What is resonance in RLC circuit?', ['When capacitive and inductive reactance are equal', 'When resistance is zero', 'When current stops', 'When voltage spikes'], 0),
                ('Which element passes current in one direction only?', ['Resistor', 'Capacitor', 'Diode', 'Inductor'], 2),
                ('What is a Thevenin equivalent?', ['Simplified circuit with voltage source and series resistance', 'Parallel current source', 'Transformer model', 'Filter design'], 0),
                ('What is power in an AC circuit?', ['V x I × cosθ', 'V + I', 'I / V', 'V^2 + I^2'], 0),
            ]),
            ('eee-power-electronics', 'Power Electronics', '📟', [
                ('What does a converter do?', ['Reduce noise', 'Change DC to AC or AC to DC', 'Measure voltage', 'Store energy'], 1),
                ('Which device is a controlled rectifier?', ['Diode', 'Thyristor', 'Resistor', 'Capacitor'], 1),
                ('What is PWM used for?', ['Pulse width modulation', 'Printing documents', 'Power generation', 'Monitoring signals'], 0),
                ('What is an inverter?', ['Converts AC to DC', 'Converts DC to AC', 'Filters harmonics', 'Steps voltage up'], 1),
                ('Which device can be switched on and off electronically?', ['Transformer', 'IGBT', 'Inductor', 'Capacitor'], 1),
                ('What is regenerative braking?', ['Wasteful energy loss', 'Recovering energy back to source', 'Starting current limit', 'Voltage regulation'], 1),
                ('Which application uses power electronics heavily?', ['Mobile apps', 'Electric drives', 'Audio streaming', 'Social media'], 1),
                ('What is harmonic distortion?', ['Pure sine wave', 'Deviation from sinusoidal waveform', 'Power factor correction', 'Voltage stabilization'], 1),
                ('Which converter is used to step down voltage?', ['Boost converter', 'Buck converter', 'Inverter', 'Filter'], 1),
                ('What is a chopper?', ['DC-DC converter', 'AC generator', 'Circuit breaker', 'Voltage regulator'], 0),
            ]),
            ('eee-control', 'Control Systems', '🎛️', [
                ('What is a feedback loop?', ['Loop of rope', 'Output feeding back as input signal', 'Open circuit', 'Power supply'], 1),
                ('Which element adjusts system input based on error?', ['Sensor', 'Controller', 'Actuator', 'Filter'], 1),
                ('What is proportional control?', ['Control action based on error magnitude', 'Control action based on error derivative only', 'On/off action', 'No control'], 0),
                ('Which response improves by integral control?', ['Steady-state error', 'System noise', 'Actuator power', 'Signal delay'], 0),
                ('What is a transfer function used for?', ['Describing system dynamics mathematically', 'Computing energy', 'Generating signals', 'Measuring temperature'], 0),
                ('What is a PID controller?', ['Proportional-Integral-Derivative controller', 'Power Input Device', 'Phase In Delay', 'Programmable Interface Device'], 0),
                ('Which criterion assesses stability from pole locations?', ['Nyquist', 'Routh-Hurwitz', 'Monte Carlo', 'Least squares'], 1),
                ('What does open-loop control mean?', ['Control without feedback', 'Feedback control', 'Adaptive control', 'Digital control'], 0),
                ('Which parameter affects damping ratio?', ['Mass only', 'System parameters in transfer function', 'Voltage only', 'Current only'], 1),
                ('What is servo control commonly used for?', ['Precise motion control', 'Email delivery', 'Database queries', 'Audio playback'], 0),
            ]),
            ('eee-measurements', 'Electrical Measurements', '📏', [
                ('Which instrument measures voltage?', ['Ammeter', 'Voltmeter', 'Wattmeter', 'Oscilloscope'], 1),
                ('What is a current transformer used for?', ['Measuring high currents safely', 'Converting voltage', 'Filtering signals', 'Storing charge'], 0),
                ('Which device measures power?', ['Voltmeter', 'Ammeter', 'Wattmeter', 'Ohmmeter'], 2),
                ('What is accuracy in measurement?', ['Closeness to true value', 'Repeatability', 'Resolution', 'Range'], 0),
                ('Which instrument displays waveform shapes?', ['Voltmeter', 'Ammeter', 'Oscilloscope', 'Wattmeter'], 2),
                ('What does calibration ensure?', ['Instrument reliability and correctness', 'Faster speed', 'Larger range', 'More power'], 0),
                ('Which device measures resistance?', ['Ohmmeter', 'Voltmeter', 'Ammeter', 'Wattmeter'], 0),
                ('What is resolution of an instrument?', ['Smallest detectable change', 'Maximum value', 'Power consumption', 'Size'], 0),
                ('What is a transducer?', ['Converts one form of energy to another', 'Stores electrical charge', 'Magnifies signals', 'Generates noise'], 0),
                ('Which property is affected by temperature in measurements?', ['Torque', 'Resistance', 'Network latency', 'Software version'], 1),
            ]),
            ('eee-renewable', 'Renewable Energy', '🌿', [
                ('Which source is renewable?', ['Coal', 'Oil', 'Wind', 'Natural gas'], 2),
                ('What does PV stand for in solar systems?', ['Power Voltage', 'PhotoVoltaic', 'Pulse Vibration', 'Potential Value'], 1),
                ('Which energy source is variable and weather-dependent?', ['Nuclear', 'Wind', 'Geothermal', 'Natural gas'], 1),
                ('What is energy storage used for in renewables?', ['Waste disposal', 'Balancing supply and demand', 'Cooling systems', 'Data backup'], 1),
                ('Which device converts sunlight to electricity?', ['Wind turbine', 'Solar panel', 'Hydro turbine', 'Battery'], 1),
                ('What is grid parity?', ['Equal time zones', 'When renewable energy cost equals conventional power', 'Same voltage levels', 'Network topology'], 1),
                ('Which renewable system uses flowing water?', ['Solar', 'Wind', 'Hydro', 'Biomass'], 2),
                ('What is net metering?', ['Measuring power factor', 'Selling excess generated energy back to grid', 'Monitoring voltage', 'Controlling frequency'], 1),
                ('What is a bioenergy source?', ['Wind', 'Solar', 'Biomass', 'Nuclear'], 2),
                ('Which renewable technology uses blades and a generator?', ['Solar PV', 'Wind turbine', 'Hydro dam', 'Geothermal pump'], 1),
            ]),
            ('eee-transmission', 'Transmission & Distribution', '🛣️', [
                ('What voltage level is typical for long-distance transmission?', ['Low voltage', 'Medium voltage', 'High voltage', 'Extra-low voltage'], 2),
                ('Why is high voltage used for transmission?', ['Reduce current and losses', 'Increase heat', 'Simplify insulation', 'Improve power factor'], 0),
                ('What does a transformer do in transmission?', ['Change voltage level', 'Measure current', 'Store energy', 'Split phases'], 0),
                ('What is a substation?', ['Plant for power generation', 'Facility for voltage conversion and switching', 'Wind farm location', 'Battery storage area'], 1),
                ('Which line protects against faults?', ['Pilot line', 'Transmission line', 'Distribution line', 'Communication line'], 0),
                ('What is radial distribution?', ['Single path from source to load', 'Multiple loops', 'Wireless distribution', 'Direct current only'], 0),
                ('Which conductor is used in overhead lines?', ['Copper', 'Aluminum', 'Optical fiber', 'Plastic'], 1),
                ('What does SCADA monitor in power systems?', ['Financial data', 'Network health and equipment', 'Student attendance', 'Software updates'], 1),
                ('Which voltage is stepped down for local distribution?', ['Extra-high voltage', 'High voltage', 'Medium voltage', 'Low voltage'], 3),
                ('What is power loss in transmission mainly due to?', ['Capacitance', 'Inductance', 'Resistance heating', 'Magnetism'], 2),
            ]),
        ],
    },
    'Civil': {
        'name': 'Civil Engineering',
        'timer': 560,
        'level': 'Medium',
        'subjects': [
            ('civil-structural', 'Structural Engineering', '🏗️', [
                ('What is beam bending moment?', ['Force at a support', 'Internal moment due to load', 'Shear stress', 'Deflection'], 1),
                ('Which material resists tension best?', ['Concrete', 'Steel', 'Brick', 'Glass'], 1),
                ('What does load factor account for?', ['Safety and uncertainty in design', 'Material cost', 'Project schedule', 'Aesthetic appeal'], 0),
                ('What is a column?', ['Horizontal support member', 'Vertical compression member', 'Surface finish', 'Foundation type'], 1),
                ('Which method determines deflection in beams?', ['Area-moment method', 'Euler method', 'Runge-Kutta', 'Newton-Raphson'], 0),
                ('What is shear force?', ['Force causing sliding between sections', 'Twisting force', 'Longitudinal compression', 'Thermal stress'], 0),
                ('Which structure type is truss?', ['Solid wall', 'Framework of members', 'Masonry arch', 'Cable-stayed bridge'], 1),
                ('What is section modulus used for?', ['Calculating shear stress', 'Designing beam strength', 'Estimating concrete volume', 'Soil testing'], 1),
                ('What is allowable stress?', ['Stress determined by material capacity with safety factor', 'Maximum applied stress', 'Thermal stress', 'Service load'], 0),
                ('What is the primary function of a bridge?', ['Electrical transmission', 'Vehicular and pedestrian crossing', 'Water storage', 'Airflow control'], 1),
            ]),
            ('civil-surveying', 'Surveying', '📏', [
                ('What is a theodolite used for?', ['Measuring angles in horizontal and vertical planes', 'Testing soil', 'Mixing concrete', 'Measuring voltage'], 0),
                ('What is leveling in surveying?', ['Determining height differences', 'Measuring distances', 'Creating blueprints', 'Sampling soil'], 0),
                ('Which instrument measures distance electronically?', ['Total station', 'Plumb bob', 'Compass', 'Theodolite'], 0),
                ('What is a benchmark?', ['Reference point with known elevation', 'A bridge type', 'Survey map', 'Construction material'], 0),
                ('Which survey uses GPS technology?', ['Preliminary survey', 'Control survey', 'GPS survey', 'Contour survey'], 2),
                ('What is triangulation?', ['Measuring area of triangles', 'Using triangles to determine positions', 'Mixing concrete in shapes', 'Testing structural strength'], 1),
                ('Which method maps terrain elevation?', ['Contour surveying', 'Hydrographic surveying', 'Traffic surveying', 'Photogrammetry'], 0),
                ('What is a traverse in surveying?', ['Series of connected survey lines', 'Single measurement', 'Soil test', 'Structural analysis'], 0),
                ('What is EDM in surveying?', ['Electronic distance measurement', 'Engineering design method', 'Earth density modulus', 'Environmental development map'], 0),
                ('Which factor affects survey accuracy?', ['Instrument precision', 'Weather conditions', 'Operator skill', 'All of the above'], 3),
            ]),
            ('civil-geotechnical', 'Geotechnical Engineering', '🪨', [
                ('What is soil bearing capacity?', ['Resistance of soil to shear', 'Ability of soil to support loads', 'Permeability rating', 'Soil color'], 1),
                ('Which test measures soil strength?', ['Proctor test', 'California bearing ratio', 'Direct shear test', 'Slump test'], 2),
                ('What is a borehole used for?', ['Foundation design', 'Collecting soil samples', 'Testing concrete', 'Surveying boundaries'], 1),
                ('Which soil has highest permeability?', ['Clay', 'Silt', 'Gravel', 'Peat'], 2),
                ('What is consolidation?', ['Increase in soil volume', 'Decrease in soil volume due to compression', 'Soil mixing', 'Fundamental frequency'], 1),
                ('What is a retaining wall designed to do?', ['Support vertical loads only', 'Hold back soil or rock', 'Carry water', 'Store equipment'], 1),
                ('Which soil property influences settlement?', ['Color', 'Moisture content', 'Particle shape', 'Gravity'], 1),
                ('What is a slope stability analysis used for?', ['Designing columns', 'Preventing landslides', 'Calculating beam strength', 'Estimating thermal loads'], 1),
                ('Which material is used in foundation backfill?', ['Sand', 'Bitumen', 'Glass', 'Wood'], 0),
                ('What is plastic limit in soils?', ['Moisture content at which soil starts to crumble', 'Maximum dry density', 'Shear strength', 'Permeability'], 0),
            ]),
            ('civil-construction', 'Construction Management', '🏢', [
                ('What is CPM used for?', ['Quality control', 'Project scheduling and management', 'Soil testing', 'Structure design'], 1),
                ('Which document defines resources and timeline?', ['Blueprint', 'Construction schedule', 'Material certificate', 'Survey map'], 1),
                ('What is cost estimation?', ['Measuring dimensions', 'Predicting project expenses', 'Testing soil', 'Approving permits'], 1),
                ('Which contract type fixes total project cost?', ['Lump-sum contract', 'Cost-plus contract', 'Time and materials', 'Unit price'], 0),
                ('What does scope management control?', ['Project boundaries and deliverables', 'Soil composition', 'Team payroll', 'Legal disputes'], 0),
                ('Which activity monitors construction progress?', ['Site inspection', 'Sales meeting', 'Coding', 'Transformer testing'], 0),
                ('What is value engineering?', ['Improving project value while reducing cost', 'Increasing project duration', 'Adding extra materials', 'Monitoring weather'], 0),
                ('Which quality standard applies to construction management?', ['ISO 9001', 'IEEE 802.11', 'SQL 2003', 'HTTP 2'], 0),
                ('What is a Gantt chart used for?', ['Scheduling tasks', 'Designing structures', 'Financial auditing', 'Soil analysis'], 0),
                ('Which document records project changes?', ['Change order', 'Blueprint', 'Invoice', 'Resume'], 0),
            ]),
            ('civil-transportation', 'Transportation Engineering', '🚧', [
                ('What is a traffic volume study?', ['Analyzing vehicle flow on roads', 'Measuring population density', 'Calculating structural load', 'Testing concrete strength'], 0),
                ('Which design element improves road safety?', ['Sharp curves', 'Guardrails', 'Narrow lanes', 'Poor signage'], 1),
                ('What is pavement thickness based on?', ['Traffic load and soil strength', 'Color of asphalt', 'Nearby buildings', 'Air quality'], 0),
                ('Which mode is part of multimodal transport?', ['Walking', 'Air travel', 'Rail', 'All of the above'], 3),
                ('What is Level of Service (LOS)?', ['Road capacity', 'Traffic quality of service rating', 'Vehicle speed', 'Ticket price'], 1),
                ('Which intersection type reduces conflict points?', ['Unsignalized intersection', 'Roundabout', 'T intersection', 'Four-way stop'], 1),
                ('What is geometric design focused on?', ['Road alignment and profile', 'Concrete mix', 'Electrical layout', 'Landscape design'], 0),
                ('What is the function of drainage in road design?', ['Provide lighting', 'Carry water away', 'Increase speed', 'Reduce noise'], 1),
                ('Which vehicle class influences pavement design?', ['Cars', 'Trucks', 'Buses', 'All of the above'], 3),
                ('What is a traffic signal phase?', ['Single cycle of all lights', 'Duration for each signal state', 'Number of lanes', 'Road width'], 1),
            ]),
            ('civil-environmental', 'Environmental Engineering', '🌳', [
                ('What is wastewater treatment used for?', ['Generating electricity', 'Removing contaminants from water', 'Building roads', 'Measuring traffic'], 1),
                ('Which pollutant is regulated in air quality?', ['Carbon monoxide', 'Concrete dust', 'Noise', 'Soil moisture'], 0),
                ('What is a sedimentation tank?', ['Structure for settling solids from water', 'Mixing chemicals', 'Electric transformer', 'Survey instrument'], 0),
                ('Which treatment removes pathogens from water?', ['Sedimentation', 'Chlorination', 'Screening', 'Aeration'], 1),
                ('What is a leachate in landfills?', ['Liquid drained from waste', 'Solid waste layer', 'Noise barrier', 'Air pollutant'], 0),
                ('What does an environmental impact assessment evaluate?', ['Project financials', 'Environmental consequences of construction', 'Employee performance', 'Software bugs'], 1),
                ('Which system conserves rainwater?', ['Stormwater harvesting', 'Pavement design', 'Structural analysis', 'Traffic control'], 0),
                ('What is a bioswale used for?', ['Stormwater filtration', 'Road marking', 'Building insulation', 'Load distribution'], 0),
                ('Which test measures soil contamination?', ['Proctor test', 'pH and heavy metal analysis', 'Direct shear', 'Compression test'], 1),
                ('What is sustainable design?', ['Maximizing cost only', 'Meeting present needs without compromising future generations', 'Ignoring regulations', 'Using maximum energy'], 1),
            ]),
            ('civil-concrete', 'Concrete Technology', '🧱', [
                ('Which ingredient is not part of concrete?', ['Cement', 'Water', 'Sand', 'Wood'], 3),
                ('What is slump test used for?', ['Measuring concrete strength', 'Testing workability', 'Checking curing time', 'Evaluating color'], 1),
                ('Which property does admixture improve?', ['Workability', 'Electrical conductivity', 'Magnetic permeability', 'Soil bearing'], 0),
                ('What is curing?', ['Keeping concrete moist to gain strength', 'Mixing ingredients', 'Breaking concrete', 'Drying wood'], 0),
                ('What does compressive strength measure?', ['Tensile resistance', 'Load concrete can withstand under compression', 'Flexural strength', 'Density'], 1),
                ('Which cement type is used for faster setting?', ['Ordinary Portland Cement', 'Rapid hardening cement', 'Low heat cement', 'White cement'], 1),
                ('What is the typical water-cement ratio range?', ['0.2-0.3', '0.4-0.6', '0.7-0.9', '1.0-1.2'], 1),
                ('Which aggregate is coarse?', ['Sand', 'Gravel', 'Clay', 'Silt'], 1),
                ('What causes segregation in concrete?', ['Too much water and improper handling', 'Proper curing', 'Low temperature', 'Correct mix'], 0),
                ('What is air entrainment used for?', ['Increasing density', 'Improving freeze-thaw resistance', 'Reducing strength', 'Changing color'], 1),
            ]),
            ('civil-fluid', 'Fluid Mechanics', '🌊', [
                ('What is viscosity?', ['Measure of fluid density', 'Resistance to flow', 'Speed of sound in fluid', 'Pressure variation'], 1),
                ('Which law relates pressure and volume of a gas?', ['Ohm’s law', 'Boyle’s law', 'Hooke’s law', 'Kirchhoff’s law'], 1),
                ('What is laminar flow?', ['Chaotic flow', 'Smooth layer flow', 'Turbulent flow', 'Compressible flow'], 1),
                ('Which instrument measures fluid pressure?', ['Thermometer', 'Barometer', 'Manometer', 'Anemometer'], 2),
                ('What does Reynolds number predict?', ['Compressibility', 'Flow regime', 'Fluid color', 'Temperature'], 1),
                ('Which equation conserves mass in fluid flow?', ['Bernoulli', 'Continuity', 'Navier-Stokes', 'Fourier'], 1),
                ('What is a boundary layer?', ['Layer of fluid with velocity gradient near surface', 'High-pressure region', 'Temperature zone', 'Acoustic layer'], 0),
                ('Which flow type has chaotic eddies?', ['Laminar', 'Turbulent', 'Steady', 'Incompressible'], 1),
                ('What is head loss?', ['Energy loss due to friction', 'Increase in pressure', 'Flow acceleration', 'Temperature rise'], 0),
                ('Which fluid is assumed incompressible in many problems?', ['Water', 'Air', 'Steam', 'Oil'], 0),
            ]),
        ],
    },
    'Mech': {
        'name': 'Mechanical Engineering',
        'timer': 600,
        'level': 'Medium',
        'subjects': [
            ('mech-thermo', 'Thermodynamics', '🔥', [
                ('What is the first law of thermodynamics?', ['Entropy always increases', 'Energy cannot be created or destroyed', 'Pressure is constant in a closed system', 'Temperature is proportional to volume'], 1),
                ('Which property measures disorder?', ['Enthalpy', 'Entropy', 'Temperature', 'Pressure'], 1),
                ('What is a heat engine?', ['Device converting heat into work', 'Refrigeration unit', 'Pump', 'Torque generator'], 0),
                ('Which cycle models ideal gas engines?', ['Otto cycle', 'Carnot cycle', 'Rankine cycle', 'Diesel cycle'], 0),
                ('What is specific heat?', ['Heat required to change temperature of unit mass by one degree', 'Heat transfer coefficient', 'Total system energy', 'Power output'], 0),
                ('Which law defines efficiency of heat engines?', ['First law', 'Second law', 'Third law', 'Zeroth law'], 1),
                ('What does enthalpy represent?', ['Internal energy plus pressure-volume product', 'Mass times velocity', 'Thermal conductivity', 'Heat flux'], 0),
                ('Which device transfers heat without moving parts?', ['Pump', 'Compressor', 'Heat exchanger', 'Turbine'], 2),
                ('What is an isobaric process?', ['Constant pressure', 'Constant volume', 'Constant temperature', 'Adiabatic process'], 0),
                ('Which process has no heat transfer?', ['Isothermal', 'Isobaric', 'Adiabatic', 'Isochoric'], 2),
            ]),
            ('mech-fluid', 'Fluid Mechanics', '💧', [
                ('What is buoyancy?', ['Force that makes objects sink', 'Upward force due to displaced fluid', 'Friction between fluids', 'Pressure at a point'], 1),
                ('Which equation expresses conservation of mass in fluids?', ['Bernoulli’s equation', 'Continuity equation', 'Navier-Stokes equation', 'Fourier equation'], 1),
                ('What is cavitation?', ['Formation of vapor bubbles in liquid', 'Fluid friction', 'Turbulent flow', 'Laminar flow'], 0),
                ('Which property determines flow regime?', ['Viscosity only', 'Reynolds number', 'Density only', 'Pressure'], 1),
                ('What is a pitot tube used for?', ['Measuring velocity head', 'Mixing fluids', 'Heating liquids', 'Filtering water'], 0),
                ('What does Bernoulli’s principle relate?', ['Pressure and velocity', 'Mass and energy', 'Temperature and volume', 'Force and torque'], 0),
                ('Which flow occurs at low Reynolds numbers?', ['Turbulent', 'Laminar', 'Compressible', 'Unsteady'], 1),
                ('What is hydraulic gradient?', ['Slope of piezometric head', 'Pressure drop per unit length', 'Velocity vector', 'Temperature gradient'], 0),
                ('Which pump uses rotation to move fluids?', ['Reciprocating pump', 'Centrifugal pump', 'Positive displacement pump', 'Vacuum pump'], 1),
                ('What is viscosity?', ['Resistance to flow', 'Density of fluid', 'Color of fluid', 'Sound speed'], 0),
            ]),
            ('mech-manufacturing', 'Manufacturing Technology', '🏭', [
                ('What is machining?', ['Forming parts by cutting', 'Assembling products', 'Testing materials', 'Packaging goods'], 0),
                ('Which process shapes metal with dies?', ['Casting', 'Forging', 'Molding', 'Welding'], 1),
                ('What is additive manufacturing?', ['Removing material to create parts', 'Adding material layer by layer to build parts', 'Joining two parts', 'Cooling components'], 1),
                ('What does CNC stand for?', ['Computer Numerical Control', 'Central Network Controller', 'Coded Numerical Circuit', 'Control Node Computer'], 0),
                ('What is a jig used for?', ['Heating materials', 'Holding workpiece during machining', 'Measuring force', 'Transporting products'], 1),
                ('Which material is melted in casting?', ['Wood', 'Metal', 'Paper', 'Rubber'], 1),
                ('What is tolerancing?', ['Allowable variation in dimensions', 'Surface finishing', 'Heat treatment', 'Quality inspection'], 0),
                ('Which manufacturing operation creates threads?', ['Boring', 'Threading', 'Drilling', 'Milling'], 1),
                ('What is a die?', ['Tool used for shaping metal', 'Measuring gauge', 'Cutting fluid', 'Heat source'], 0),
                ('Which process joins two metal pieces by heat only?', ['Welding', 'Bolting', 'Riveting', 'Adhesive bonding'], 0),
            ]),
            ('mech-cad', 'CAD/CAM', '🖥️', [
                ('What does CAD stand for?', ['Computer Aided Drafting', 'Computer Aided Design', 'Computer Algorithm Development', 'Circuit Analysis Design'], 1),
                ('What is CAM used for?', ['Designing circuits', 'Manufacturing parts from CAD models', 'Writing code', 'Testing software'], 1),
                ('Which file type is standard for 3D models?', ['PDF', 'DXF', 'STL', 'TXT'], 2),
                ('What is parametric modeling?', ['Models defined by equations and constraints', 'Static drawings only', 'Manual sketching', 'Video rendering'], 0),
                ('Which stage converts design to machine instructions?', ['Modeling', 'Simulation', 'Post-processing', 'Assembly'], 2),
                ('What is simulation in CAD/CAM?', ['Testing designs virtually before manufacturing', 'Printing the model', 'Mixing materials', 'Packaging parts'], 0),
                ('Which software is common for CAD?', ['AutoCAD', 'Excel', 'Word', 'Photoshop'], 0),
                ('What is a toolpath?', ['Path the cutting tool follows', 'Electrical wiring plan', 'Data transmission route', 'Assembly sequence'], 0),
                ('Which term refers to 3D visualization of parts?', ['Render', 'Compile', 'Encrypt', 'Deploy'], 0),
                ('What is CNC used for in CAM?', ['Manual cutting', 'Automated machining using code', 'Heating metal', 'Measuring dimensions'], 1),
            ]),
            ('mech-heat', 'Heat Transfer', '🌡️', [
                ('Which mode of heat transfer requires a fluid?', ['Conduction', 'Convection', 'Radiation', 'Conduction and radiation'], 1),
                ('What is conduction?', ['Heat transfer through direct contact', 'Heat transfer through fluid motion', 'Heat transfer through electromagnetic waves', 'Heat generation'], 0),
                ('What is radiation?', ['Heat transfer via waves', 'Heat transfer through solids', 'Heat transfer through liquids only', 'Heat storage'], 0),
                ('Which law relates heat flux to temperature gradient?', ['Newton’s law of cooling', 'Fourier’s law', 'Ohm’s law', 'Hooke’s law'], 1),
                ('What is thermal conductivity?', ['Material’s ability to conduct heat', 'Amount of stored energy', 'Rate of mass flow', 'Pressure change'], 0),
                ('What is a heat exchanger?', ['Device transferring heat between fluids', 'Power source', 'Structural component', 'Control valve'], 0),
                ('Which material is a good thermal insulator?', ['Copper', 'Aluminum', 'Air', 'Steel'], 2),
                ('What is convective heat transfer coefficient?', ['Measure of convective heat transfer effectiveness', 'Mass flow rate', 'Pressure constant', 'Voltage rating'], 0),
                ('What is a lumped system analysis assumption?', ['Temperature variation within body is negligible', 'Pressure constant only', 'Mass constant only', 'No heat transfer'], 0),
                ('Which process occurs without material motion?', ['Conduction', 'Convection', 'Radiation', 'Evaporation'], 0),
            ]),
            ('mech-design', 'Machine Design', '⚙️', [
                ('What is factor of safety?', ['Ratio of design strength to allowable stress', 'Power-to-weight ratio', 'Speed limit', 'Load capacity'], 0),
                ('Which component transmits rotational motion between shafts?', ['Belt', 'Chain', 'Gear', 'All of the above'], 3),
                ('What is fatigue failure?', ['Failure due to repetitive loading', 'Failure from a single overload', 'Failure due to corrosion', 'Failure due to heat'], 0),
                ('Which class of lever has load between effort and fulcrum?', ['First', 'Second', 'Third', 'Fourth'], 1),
                ('What is a bearing used for?', ['Support and reduce friction between moving parts', 'Store energy', 'Measure force', 'Transmit heat'], 0),
                ('Which fit is used for free movement?', ['Interference fit', 'Transition fit', 'Clearance fit', 'Shrink fit'], 2),
                ('What is a key in machine design?', ['Fastener', 'Device that locks rotating elements together', 'Paint type', 'Lubricant'], 1),
                ('Which material property is hardness?', ['Resistance to deformation', 'Electrical resistance', 'Magnetic permeability', 'Thermal conductivity'], 0),
                ('What is a spur gear used for?', ['Transmit motion between parallel shafts', 'Change fluid direction', 'Store energy', 'Provide insulation'], 0),
                ('Which process joins metal parts by heat only?', ['Welding', 'Bolting', 'Riveting', 'Adhesive bonding'], 0),
            ]),
            ('mech-industry', 'Industrial Engineering', '🏭', [
                ('What is productivity?', ['Output per unit of input', 'Number of employees', 'Working hours', 'Machine cost'], 0),
                ('What does lean manufacturing aim to eliminate?', ['Quality control', 'Waste', 'Design', 'Marketing'], 1),
                ('Which technique is used for process improvement?', ['5S', 'SWOT', 'PERT', 'IPO'], 0),
                ('What is takt time?', ['Available production time divided by demand', 'Total machine runtime', 'Product weight', 'Cost per unit'], 0),
                ('Which layout groups machines by process type?', ['Product layout', 'Functional layout', 'Fixed-position layout', 'Cellular layout'], 1),
                ('What does ergonomics focus on?', ['Product design only', 'Human interaction with systems', 'Machine reliability', 'Financial accounting'], 1),
                ('Which inventory method orders at fixed intervals?', ['EOQ', 'Periodic review', 'Just-in-time', 'ABC analysis'], 1),
                ('What is a value stream map?', ['Diagram of material and information flow', 'Financial report', 'Supply chain contract', 'Quality certificate'], 0),
                ('Which measure tracks defects per million opportunities?', ['PPM', 'ROI', 'TQM', 'KPI'], 0),
                ('What is a bottleneck in production?', ['Fastest workstation', 'Constraint limiting output', 'Quality inspection', 'Storage area'], 1),
            ]),
            ('mech-robotics', 'Robotics', '🤖', [
                ('What is an actuator in a robot?', ['Sensor', 'Control algorithm', 'Device that creates motion', 'Communication protocol'], 2),
                ('Which sensor measures distance?', ['Thermistor', 'Ultrasonic sensor', 'Microphone', 'Gyroscope'], 1),
                ('What is kinematics concerned with?', ['Energy conversion', 'Motion without forces', 'Circuit design', 'Fluid flow'], 1),
                ('Which controller type is common in robotics?', ['PID controller', 'FTP controller', 'HTML controller', 'SQL controller'], 0),
                ('What is inverse kinematics?', ['Calculating joint angles for a desired end-effector position', 'Forward motion planning', 'Signal processing', 'Data encryption'], 0),
                ('Which robot type uses multiple joints?', ['Mobile robot', 'Articulated robot', 'Fixed robot', 'Walking robot'], 1),
                ('What is a degree of freedom?', ['Number of independent motions', 'Power source', 'Control signal', 'Safety limit'], 0),
                ('Which actuation method is common in industrial robots?', ['Hydraulic', 'Resistive', 'Capacitive', 'Optical'], 0),
                ('What is path planning?', ['Designing movement trajectory', 'Building a robot', 'Measuring temperature', 'Managing inventory'], 0),
                ('Which field combines mechanics, electronics, and control?', ['Civil engineering', 'Robotics', 'Chemistry', 'Marketing'], 1),
            ]),
        ],
    },
}


def escape(text):
    return text.replace('"', '\\"').replace('\n', ' ')

with open('src/data/questions.ts', 'w', encoding='utf-8') as f:
    f.write('export interface MCQQuestion {\n')
    f.write('  id: number;\n')
    f.write('  question: string;\n')
    f.write('  options: string[];\n')
    f.write('  correct: number; // index\n')
    f.write('}\n\n')
    f.write('export interface Subject {\n')
    f.write('  id: string;\n')
    f.write('  name: string;\n')
    f.write('  icon: string;\n')
    f.write('  difficulty: "Easy" | "Medium" | "Hard";\n')
    f.write('  questions: MCQQuestion[];\n')
    f.write('}\n\n')
    f.write('export type DepartmentCode = "AIDS" | "IT" | "CSE" | "ECE" | "EEE" | "Civil" | "Mech";\n\n')
    f.write('export interface DepartmentQuestionBank {\n')
    f.write('  code: DepartmentCode;\n')
    f.write('  name: string;\n')
    f.write('  timer: number;\n')
    f.write('  level: "Easy" | "Medium" | "Hard";\n')
    f.write('  subjects: Subject[];\n')
    f.write('}\n\n')
    f.write('export const departmentKeyMap: Record<string, DepartmentCode> = {\n')
    f.write('  "Artificial Intelligence & Data Science": "AIDS",\n')
    f.write('  "Information Technology": "IT",\n')
    f.write('  "Computer Science & Engineering": "CSE",\n')
    f.write('  "Electronics & Communication Engineering": "ECE",\n')
    f.write('  "Electrical & Electronics Engineering": "EEE",\n')
    f.write('  "Civil Engineering": "Civil",\n')
    f.write('  "Mechanical Engineering": "Mech",\n')
    f.write('};\n\n')
    f.write('export const questionBank: Record<DepartmentCode, DepartmentQuestionBank> = {\n')
    for code, dept in question_bank.items():
        f.write(f'  {code}: {{\n')
        f.write(f'    code: "{code}",\n')
        f.write(f'    name: "{dept["name"]}",\n')
        f.write(f'    timer: {dept["timer"]},\n')
        f.write(f'    level: "{dept["level"]}",\n')
        f.write('    subjects: [\n')
        for sid, name, icon, qs in dept['subjects']:
            f.write('      {\n')
            f.write(f'        id: "{sid}",\n')
            f.write(f'        name: "{name}",\n')
            f.write(f'        icon: "{icon}",\n')
            difficulty = 'Hard' if code in ('AIDS', 'CSE', 'ECE') else 'Medium'
            f.write(f'        difficulty: "{difficulty}",\n')
            f.write('        questions: [\n')
            for i, (question, options, correct) in enumerate(qs, start=1):
                f.write('          {\n')
                f.write(f'            id: {i},\n')
                f.write(f'            question: "{escape(question)}",\n')
                f.write('            options: [')
                f.write(', '.join(f'"{escape(opt)}"' for opt in options))
                f.write('],\n')
                f.write(f'            correct: {correct},\n')
                f.write('          },\n')
            f.write('        ],\n')
            f.write('      },\n')
        f.write('    ],\n')
        f.write('  },\n')
    f.write('};\n\n')
    f.write('export function getDepartmentQuestionBank(departmentName: string): DepartmentQuestionBank | null {\n')
    f.write('  const key = departmentKeyMap[departmentName];\n')
    f.write('  return key ? questionBank[key] : null;\n')
    f.write('}\n\n')
    f.write('export const jobOpenings = [\n')
    f.write('  { id: 1, department: "Artificial Intelligence & Data Science", code: "AIDS", qualification: "Ph.D. in AI/DS or a related field", experience: "3+ years academic or research experience", skills: ["machine learning", "deep learning", "data science", "python", "analytics"] },\n')
    f.write('  { id: 2, department: "Information Technology", code: "IT", qualification: "Ph.D./M.Tech in IT or a related field", experience: "3+ years teaching or industry experience", skills: ["networking", "database", "cloud computing", "web development", "security"] },\n')
    f.write('  { id: 3, department: "Computer Science & Engineering", code: "CSE", qualification: "Ph.D. in CSE or a related field", experience: "3+ years teaching or research experience", skills: ["programming", "algorithms", "data structures", "operating systems", "software engineering"] },\n')
    f.write('  { id: 4, department: "Electronics & Communication Engineering", code: "ECE", qualification: "Ph.D. in ECE or a related field", experience: "3+ years teaching or research experience", skills: ["vlsi", "embedded systems", "signal processing", "communication", "microelectronics"] },\n')
    f.write('  { id: 5, department: "Electrical & Electronics Engineering", code: "EEE", qualification: "Ph.D. in EEE or a related field", experience: "3+ years teaching or research experience", skills: ["power systems", "electrical machines", "circuits", "control systems", "renewable energy"] },\n')
    f.write('  { id: 6, department: "Civil Engineering", code: "Civil", qualification: "Ph.D. in Civil Engineering or a related field", experience: "3+ years teaching or research experience", skills: ["structural engineering", "surveying", "construction", "geotechnical", "infrastructure"] },\n')
    f.write('  { id: 7, department: "Mechanical Engineering", code: "Mech", qualification: "Ph.D. in Mechanical Engineering or a related field", experience: "3+ years teaching or research experience", skills: ["thermodynamics", "manufacturing", "cad", "fluid mechanics", "mechanics"] },\n')
    f.write('];\n')
